### ISSUE TITLE
Request for Dockerfile and automated build

### ISSUE THREAD

**Issue by hunt** [longshoreman/longshoreman#9]
From https://registry.hub.docker.com/u/longshoreman/longshoreman

Should put Dockerfile source to Github repository and set to automated build with Docker public registry. it's allow us to see what it build, transparency and easy todo more.

**Comment by mikejholly** [comment]
It's already in the source.

https://github.com/longshoreman/longshoreman/blob/master/Dockerfile
https://github.com/longshoreman/longshoreman/blob/master/Makefile

**Comment by hunt** [comment]
Sorry for make it not clear. But I mean "automated build" with Docker registry
I know it in the source but it's not a trust builded

It may not important for you so never mind.
